[package]
name = "rust-grpc-greet"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
prost = "0.12.1"
tokio = { version = "1.31.0", features = ["full"] }
tonic = "0.10.2"
tonic-reflection = "0.10.2"

[build-dependencies]
tonic-build = "0.10.2"
